#!/bin/bash

set -u

usage_msg='
NAME:
  pacmanfile - Manage your pacman packages declaratively

USAGE:
  pacmanfile command

COMMANDS:
  sync   Synchronize your installed packages with your pacmanfile
'

package_manager=pacman
if [ -x "$(command -v yay)" ]; then
  package_manager=yay
fi

config_dir=${XDG_CONFIG_HOME:-$HOME/.config}

pacmanfile_packages=$(sort --unique "${config_dir}"/pacmanfile/pacmanfile*.txt | grep -E '^[^#].+')
installed_packages=$($package_manager --query --explicit --quiet | sort --unique)

function sync {
  to_install=$(diff --new-line-format="" --unchanged-line-format="" <(echo "$pacmanfile_packages") <(echo "$installed_packages"))
  if [ -n "$to_install" ]; then
    echo "$to_install" | xargs $package_manager --sync --noconfirm
  fi

  to_remove=$(diff --new-line-format="" --unchanged-line-format="" <(echo "$installed_packages") <(echo "$pacmanfile_packages"))
  if [ -n "$to_remove" ]; then
    echo "$to_remove" | xargs $package_manager --remove --nosave --recursive --noconfirm
  fi
}

if [ $# -eq 0 ]; then
  echo "$usage_msg"
  exit 1
fi

case $1 in
  sync)
    sync "$@"
    ;;

  *)
    echo "$usage_msg"
    exit 1
    ;;
esac
